[project]
authors = [{name = "Clement Sebastiao", email = "clement.sebastiao@gmail.com"}]
dependencies = ["matplotlib-map-utils>=4.0.0,<5"]
name = "paris_vote_bicycle"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tool.pixi.pypi-dependencies]
paris_vote_bicycle = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
geopandas = ">=1.1.3,<2"
statsmodels = ">=0.14.6,<0.15"
beautifulsoup4 = ">=4.14.3,<5"
pytest = ">=9.0.3,<10"
pre-commit = ">=4.6.0,<5"
libpysal = ">=4.14.1,<5"
esda = ">=2.9.0,<3"
xlrd = ">=2.0.2,<3"
